apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432 # Port exposé par le SERVICE
      targetPort: 5432 # Port exposé par le POD
      nodePort: 32432 # Port exposé par le NODE